### Testing RREF (Reduced Row Echelon Form) ###

http://www-lipn.univ-paris13.fr/~coti/doc/tutonympyscipy.pdf



In [1]:
import numpy as np

array_m = np.array([
                    [1,2,3,4],
                    [1,1,1,1],
                    [2,3,4,5]])

permutation_matrix = np.matrix([
                    [0,1,0,],
                    [1,0,0,],
                    [0,0,1,]])

line_vector = np.array([1,5,7]).reshape(1,3)

print('array_m:\n', array_m)
matrix_m = np.matrix(array_m)
print('matrix_m:\n', matrix_m)

print('permutated matrix: \n', permutation_matrix * matrix_m)

array_v = np.array([1,2,3,4])
print('array_v:\n', array_v)
# column vector}
vector_v = array_v.reshape(4,1)
print('vector_v:\n', vector_v)

print('line vector:\n', line_vector)

#vector_v = np.vectorize(array_v)
#print('vector_v:\n', vector_v)

print('array * [1,2,3,4] =\n', array_m*array_v)
print('[1,5,7] * matrix =\n',line_vector*matrix_m)
print('matrix * [1,2,3,4] =\n',matrix_m*vector_v)


mrref = sympy.Matrix(matrix_m).rref()
print(mrref)
mrref = np.matrix(np.array(mrref[0].tolist(), dtype=int))
print(mrref)

print('mref * [1,2,3,4] =\n', mrref*vector_v)
print('mref * [1,2,3,4] =\n',line_vector* mrref)


array_m:
 [[1 2 3 4]
 [1 1 1 1]
 [2 3 4 5]]
matrix_m:
 [[1 2 3 4]
 [1 1 1 1]
 [2 3 4 5]]
permutated matrix: 
 [[1 1 1 1]
 [1 2 3 4]
 [2 3 4 5]]
array_v:
 [1 2 3 4]
vector_v:
 [[1]
 [2]
 [3]
 [4]]
line vector:
 [[1 5 7]]
array * [1,2,3,4] =
 [[ 1  4  9 16]
 [ 1  2  3  4]
 [ 2  6 12 20]]
[1,5,7] * matrix =
 [[20 28 36 44]]
matrix * [1,2,3,4] =
 [[30]
 [10]
 [40]]


NameError: name 'sympy' is not defined

## R = n < m, 0 or 1 solution

In [2]:

import numpy as np
import sympy

A = np.matrix([
        [3,2],
        [5,4],
        [-1,10],
        [4,1]
])

sympy.Matrix(A).rref()



(Matrix([
 [1.0,   0],
 [  0, 1.0],
 [  0,   0],
 [  0,   0]]), [0, 1])

## R = m < n, Inifinity of solutions##  Case where we have more unknown than equations
This case is in the course 9. 
Suppose A is m by n, with m < n. Then there are non zero solutions to Ax = 0.
** Reason is : there will be free variables **


In [3]:

import numpy as np
import sympy

A = sympy.Matrix([
        [3,5,-1,4],
        [2,4,10,1]
])

R = sympy.Matrix(A).rref()
print(R)

b = sympy.Matrix([1,1,3,4]) # choose whatever I want, there will always be an infinity of solution...
x, y, z = sympy.symbols('x, y, z')
print(b)
#soln = A.LUsolve(b)

#soln = A.solve(b)
soln = sympy.solve_linear_system(A,b)
print(soln)
soln = sympy.solve_linear_system(A,x,y,z)
print(soln)

# Ax = 0
b = sympy.Matrix([0,0,0,0]) # choose whatever I want, there will always be an infinity of solution...
soln = sympy.solve_linear_system(A,x,y,z)
print(soln)

(Matrix([
[1, 0, -27, 11/2],
[0, 1,  16, -5/2]]), [0, 1])
Matrix([[1], [1], [3], [4]])
[]
{y: -16*z - 5/2, x: 27*z + 11/2}
{y: -16*z - 5/2, x: 27*z + 11/2}


## r < m, r < n, 0 or infinity of solutions


In [4]:

import numpy as np
import sympy

A = np.matrix([
        [3,5,-1],
        [6,10,-2],
        [2,4,10]
])

sympy.Matrix(A).rref()

(Matrix([
 [1.0,   0, -27.0],
 [  0, 1.0,  16.0],
 [  0,   0,     0]]), [0, 1])


## r = m = n, exactly one solution

In [5]:

import numpy as np
import sympy

A = sympy.Matrix([
        [3,5,-1],
        [6,7,-2],
        [2,4,10]
])

R = sympy.Matrix(A).rref()
print(R)
x = sympy.Matrix(3,1,[3,7,5])
b = A*x
soln = A.LUsolve(b)
print(soln)

b = sympy.Matrix(3,1,[3,2,1]) # choose whatever I want, there will always be on solution...
soln = A.LUsolve(b)
print(soln)


(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), [0, 1, 2])
Matrix([[3], [7], [5]])
Matrix([[-41/32], [4/3], [-17/96]])


In [6]:
import sympy
from sympy.interactive.printing import init_printing
init_printing(use_unicode=False, wrap_line=False, no_global=True)

sympy.Matrix([[1, 2, 3]])

[1  2  3]

In [7]:
sympy.Matrix([1, 2, 3])

[1]
[ ]
[2]
[ ]
[3]

## Check that a bunch of vectors is a BASIS

In [8]:

import numpy as np
import sympy

A = np.matrix([
        [1,2,3],
        [1,2,4],
        [2,5,8]
])

print(sympy.Matrix(A).rref())

# but this one not (not invertible, so it is not a BASIS)
A = np.matrix([
        [1,2,3],
        [1,2,3],
        [2,5,8]
])

sympy.Matrix(A).rref()

(Matrix([
[1.0,   0,   0],
[  0, 1.0,   0],
[  0,   0, 1.0]]), [0, 1, 2])


([1.0   0   -1.0], [0, 1])
 [              ]         
 [ 0   1.0  2.0 ]         
 [              ]         
 [ 0    0    0  ]         

In [9]:
import numpy as np
import sympy

A = sympy.Matrix([
        [1,2,3,1],
        [1,1,2,1],
        [1,2,3,1]
])

R = sympy.Matrix(A).rref()
print(R)

b = sympy.Matrix([1,1,3,4]) # choose whatever I want, there will always be an infinity of solution...
x, y, z = sympy.symbols('x, y, z')
print(b)
#soln = A.LUsolve(b)

#soln = A.solve(b)
soln = sympy.solve_linear_system(A,b)
print(soln)
soln = sympy.solve_linear_system(A,x,y,z)
print(soln)


(Matrix([
[1, 0, 1, 1],
[0, 1, 1, 0],
[0, 0, 0, 0]]), [0, 1])
Matrix([[1], [1], [3], [4]])
[]
{y: -z, x: -z + 1}


In [10]:
import sympy
import math

A = sympy.Matrix([
        [0,1],
        [1,1]
])

E = sympy.Matrix([
    [2,2],
    [1+math.sqrt(5), 1-math.sqrt(5)]
])

EP = A*E
print('EP = ', EP)
EP = 2*EP
print('EP = ', EP)

Res = E.inv() * EP
print(Res)

print(A.inv()*(E+E+E)*A)


EP =  Matrix([[3.23606797749979, -1.23606797749979], [5.23606797749979, 0.763932022500210]])
EP =  Matrix([[6.47213595499958, -2.47213595499958], [10.4721359549996, 1.52786404500042]])
Matrix([[3.23606797749979, -1.11022302462516e-16], [0, -1.23606797749979]])
Matrix([[-9.70820393249937, -6.00000000000000], [6, 12]])


In [11]:
## the same with numpy only
import math
import numpy as np

A = numpy.array([
        [0,1],
        [1,1]
])

E = numpy.array([
    [2,2],
    [1+math.sqrt(5), 1-math.sqrt(5)]
])

EP = np.dot(A,E)
print('EP = ', EP)
EP = 2*EP
print('EP = ', EP)
Res = E.inv() * EP
print(Res)

print(A.inv()*(E+E+E)*A)


NameError: name 'numpy' is not defined

In [12]:
import sympy

A = sympy.Matrix([
        [5,2,1],
        [4,7,6],
        [6,3,9]
    ])

print(A.det())

print('EigenValues : ', A.eigenvals())
#print('EigenVectors : ', A.eigenvects())

A = sympy.Matrix([
        [1,1],
        [1,0]
])

print(A.det())

print('EigenValues : ', A.eigenvals())
print('EigenVectors : ', A.eigenvects())


195
EigenValues :  {12/(4*sqrt(61) + 52)**(1/3) + (4*sqrt(61) + 52)**(1/3) + 7: 1, 7 + (-1/2 - sqrt(3)*I/2)*(4*sqrt(61) + 52)**(1/3) + 12/((-1/2 - sqrt(3)*I/2)*(4*sqrt(61) + 52)**(1/3)): 1, 7 + 12/((-1/2 + sqrt(3)*I/2)*(4*sqrt(61) + 52)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(4*sqrt(61) + 52)**(1/3): 1}
-1
EigenValues :  {1/2 + sqrt(5)/2: 1, -sqrt(5)/2 + 1/2: 1}
EigenVectors :  [(1/2 + sqrt(5)/2, 1, [Matrix([
[-1/(-sqrt(5)/2 + 1/2)],
[                    1]])]), (-sqrt(5)/2 + 1/2, 1, [Matrix([
[-1/(1/2 + sqrt(5)/2)],
[                   1]])])]


In [13]:
import numpy as np
from numpy import linalg as LA
w, v = LA.eig(np.array([
        [5,2,1],
        [4,7,6],
        [6,3,9]
    ]))
print(w, v)
w, v = LA.eig(np.array([
        [1,1],
        [1,0]
    ]))
print(w, v)


[ 14.11461811+0.j           3.44269094+1.40119349j   3.44269094-1.40119349j] [[ 0.22779400+0.j         -0.21449442-0.50487372j -0.21449442+0.50487372j]
 [ 0.69939706+0.j          0.63851462+0.j          0.63851462-0.j        ]
 [ 0.67746117+0.j         -0.23556936+0.48569623j -0.23556936-0.48569623j]]
[ 1.61803399 -0.61803399] [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [14]:
#1/(1-x) = SUM(x**n)

x = (1/3) # cas intéressant
s = 0
for i in range(100):
    s = s + x**i

print('Sum = ', s)
print('1/(1-x) = ', 1/(1-x))

Sum =  1.5
1/(1-x) =  1.4999999999999998
